import { Platform, StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  safeAreaInner: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 10,
    gap: 14,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 8,
  },
  shell: {
    borderRadius: 30,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.primaryLighter,
    backgroundColor: colors.white,
    width: '100%',
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  kicker: {
    color: colors.primary,
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 28,
  },
  logoWordmark: {
    alignSelf: 'center',
    width: 250,
    height: 48,
    marginBottom: 2,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.textDark,
    textAlign: 'center',
  },
  onboardingIconWrap: {
    alignSelf: 'center',
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingImage: {
    alignSelf: 'center',
    width: '100%',
    height: 220,
    marginVertical: 8,
  },
  cardIllustration: {
    alignSelf: 'center',
    width: '100%',
    height: 140,
    marginBottom: 8,
    borderRadius: 16,
    overflow: 'hidden',
  },
  emptyStateWrap: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  homeHeroImage: {
    alignSelf: 'center',
    width: '100%',
    height: 200,
    marginVertical: 12,
    borderRadius: 20,
    overflow: 'hidden',
  },
  subtitle: {
    color: colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
    fontSize: 15,
  },
  heroSubtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '500',
    paddingHorizontal: 12,
  },
  heroButton: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 28,
    alignSelf: 'center',
    marginTop: 14,
  },
  heroButtonText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 16,
  },
  onboardingDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  onboardingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryLight,
  },
  onboardingDotActive: {
    backgroundColor: colors.primary,
    width: 22,
  },
  locationPill: {
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationPin: {
    fontSize: 18,
  },
  locationText: {
    color: colors.textDark,
    fontSize: 15,
    fontWeight: '500',
    flexShrink: 1,
  },
  profileCard: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    shadowColor: colors.textDark,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarIcon: {
    fontSize: 28,
  },
  profileBody: {
    flex: 1,
    gap: 2,
  },
  profileName: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
  },
  profileMeta: {
    color: colors.textDark,
    fontSize: 14,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  expandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  expandLabel: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  connectionButton: {
    borderRadius: 18,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectionOn: {
    backgroundColor: '#16a34a',
  },
  connectionOff: {
    backgroundColor: '#ef4444',
  },
  emergencyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#ef4444',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  emergencyButtonText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  connectionButtonText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  sessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  notificationSummary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  notificationBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.warningBg,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  sessionText: {
    flex: 1,
    color: colors.textDark,
    fontWeight: '700',
    fontSize: 14,
  },
  card: {
    borderRadius: 22,
    padding: 12,
    gap: 8,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    shadowColor: colors.textDark,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.textDark,
  },
  cardSubtitle: {
    color: colors.textDark,
    fontSize: 15,
  },
  identityHint: {
    color: colors.primaryDark,
    fontSize: 14,
    marginBottom: 8,
  },
  stack: {
    gap: 8,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  flex: {
    flex: 1,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 17,
    color: colors.textDark,
    backgroundColor: colors.primaryLighter,
    minHeight: 52,
  },
  segmented: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  segment: {
    flexGrow: 1,
    flexBasis: '30%',
    minHeight: 54,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
  },
  segmentActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  segmentText: {
    color: colors.textDark,
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 15,
  },
  segmentTextActive: {
    color: colors.white,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.2,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  primaryButtonBusy: {
    opacity: 0.7,
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 17,
  },
  secondaryButton: {
    backgroundColor: colors.primaryLighter,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.textDark,
    fontWeight: '700',
    fontSize: 16,
  },
  secondaryButtonCompact: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 120,
    minHeight: 44,
  },
  secondaryButtonTextCompact: {
    fontSize: 15,
  },
  list: {
    gap: 12,
  },
  mapContainer: {
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  mapContainerCompact: {
    borderRadius: 14,
  },
  map: {
    width: '100%',
    height: 170,
  },
  mapCompact: {
    height: 130,
  },
  mapUnavailable: {
    minHeight: 170,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: colors.primaryLighter,
  },
  item: {
    padding: 10,
    borderRadius: 16,
    backgroundColor: colors.primaryLight,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 6,
  },
  chatBubble: {
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
  },
  chatBubbleCustomer: {
    backgroundColor: colors.primaryLighter,
    borderColor: colors.primaryLighter,
  },
  chatBubbleMechanic: {
    backgroundColor: '#d9f3e4',
    borderColor: '#92d6ad',
  },
  chatBubbleAdmin: {
    backgroundColor: colors.warningBg,
    borderColor: colors.accent,
  },
  chatSender: {
    color: colors.textDark,
    fontSize: 12,
    fontWeight: '800',
  },
  notificationItem: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 6,
  },
  notificationItemRead: {
    opacity: 0.72,
  },
  itemTitle: {
    fontWeight: '800',
    fontSize: 17,
    color: colors.textDark,
  },
  itemText: {
    color: colors.textDark,
    fontSize: 16,
  },
  smallText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  publicProfileBox: {
    gap: 4,
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLighter,
  },
  publicProfileTitle: {
    color: colors.textDark,
    fontWeight: '800',
    fontSize: 13,
  },
  coverPhoto: {
    width: '100%',
    height: 150,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: colors.primaryLighter,
  },
  galleryRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  galleryPhoto: {
    width: 92,
    height: 92,
    borderRadius: 12,
    backgroundColor: colors.primaryLighter,
  },
  reviewCard: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 4,
  },
  reviewTitle: {
    color: colors.textDark,
    fontSize: 12,
    fontWeight: '800',
  },
  calendarStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  calendarChip: {
    minWidth: 70,
    minHeight: 62,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  calendarChipText: {
    color: colors.textDark,
    fontSize: 10,
    fontWeight: '700',
  },
  calendarChipTextActive: {
    color: colors.white,
  },
  slotRow: {
    gap: 6,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: colors.primaryLight,
  },
  slotCard: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLighter,
    gap: 4,
  },
  slotCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  statusPill: {
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  statusPillText: {
    color: colors.textDark,
    fontSize: 12,
    fontWeight: '600',
  },
  toastWrap: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 24,
    left: 16,
    right: 16,
    zIndex: 50,
    alignItems: 'center',
  },
  toastCard: {
    maxWidth: 480,
    width: '100%',
    backgroundColor: colors.textDark,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  toastText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  badge: {
    color: colors.textDark,
    fontSize: 12,
    fontWeight: '700',
  },
  bottomNavDock: {
    paddingHorizontal: 14,
    paddingBottom: Platform.OS === 'android' ? 6 : 0,
    backgroundColor: 'transparent',
  },
  bottomNav: {
    backgroundColor: colors.primaryLight,
    borderRadius: 28,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottomNavItem: {
    color: colors.textDark,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
    marginTop: 2,
  },
  bottomNavItemActive: {
    color: colors.white,
  },
  bottomNavButton: {
    borderRadius: 20,
    minWidth: 62,
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  bottomNavButtonActive: {
    backgroundColor: colors.primary,
  },
});
