import { Platform, StyleSheet } from 'react-native';
import { colors } from './colors';
import { fonts } from './fonts';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bgApp,
  },
  safeAreaInner: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 10,
    gap: 14,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 8,
  },
  appShell: {
    gap: 14,
    width: '100%',
  },
  kicker: {
    color: colors.primary,
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontSize: 28,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  topBarGreeting: {
    flexShrink: 1,
    textAlign: 'right',
    fontSize: 15,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  topBarGreetingName: {
    fontFamily: fonts.bold,
    color: colors.textDark,
  },
  logoWordmark: {
    alignSelf: 'flex-start',
    width: 130,
    height: 25,
  },
  title: {
    fontSize: 24,
    fontFamily: fonts.extrabold,
    color: colors.textDark,
    textAlign: 'center',
  },
  onboardingIconWrap: {
    alignSelf: 'center',
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeHeroImage: {
    alignSelf: 'center',
    width: '100%',
    height: 200,
    marginVertical: 12,
    borderRadius: 20,
    overflow: 'hidden',
  },
  heroPlaceholder: {
    width: '100%',
    height: 160,
    borderRadius: 20,
    marginVertical: 12,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoAddTile: {
    height: 150,
    marginVertical: 0,
    gap: 8,
  },
  photoAddText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  galleryAddTile: {
    width: 92,
    height: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    backgroundColor: colors.primaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryAddText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 12,
  },
  photoRemoveButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(11,15,34,0.7)',
  },
  placeholderCompact: {
    height: 110,
    marginVertical: 4,
  },
  screenStack: {
    gap: 14,
  },
  emptyState: {
    alignItems: 'center',
    gap: 6,
  },
  emptyStateTitle: {
    fontFamily: fonts.extrabold,
    fontSize: 17,
    color: colors.textDark,
    textAlign: 'center',
  },
  emptyStateText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontFamily: fonts.regular,
    textAlign: 'center',
    marginBottom: 4,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoRowText: {
    flex: 1,
    color: colors.textDark,
    fontSize: 15,
    fontFamily: fonts.regular,
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  itemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  itemActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  statusPillDone: {
    backgroundColor: '#d9f3e4',
    borderColor: '#d9f3e4',
  },
  statusPillTextDone: {
    color: '#15803d',
  },
  statusPillMuted: {
    backgroundColor: colors.primaryLighter,
    borderColor: colors.primaryLight,
  },
  statusPillTextMuted: {
    color: colors.textSecondary,
  },
  trustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  trustBadge: {
    flexGrow: 1,
    flexBasis: '46%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  trustBadgeText: {
    flex: 1,
    fontSize: 12,
    fontFamily: fonts.semibold,
    color: colors.textDark,
  },
  whenOption: {
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
    gap: 4,
  },
  choiceHalf: {
    flexGrow: 1,
    flexBasis: '46%',
  },
  whenOptionActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  whenOptionTitle: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: colors.textDark,
  },
  whenOptionTitleActive: {
    color: colors.primaryDark,
  },
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  backButtonSpacer: {
    width: 44,
    height: 44,
  },
  progressList: {
    gap: 10,
    paddingVertical: 4,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.primaryLight,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDotDone: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  progressDotActive: {
    backgroundColor: colors.white,
    borderWidth: 5,
  },
  progressLabel: {
    fontSize: 15,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  progressLabelDone: {
    color: colors.textDark,
  },
  progressLabelActive: {
    fontFamily: fonts.bold,
    color: colors.primaryDark,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  callButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#16a34a',
  },
  callButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  nextStepButton: {
    minHeight: 64,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
  },
  nextStepButtonText: {
    color: colors.white,
    fontFamily: fonts.extrabold,
    fontSize: 19,
    letterSpacing: 0.3,
  },
  incomingScreen: {
    flex: 1,
    backgroundColor: colors.bgApp,
    paddingHorizontal: 16,
    paddingVertical: 20,
    justifyContent: 'space-between',
    gap: 16,
  },
  incomingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  incomingTitle: {
    fontSize: 28,
    fontFamily: fonts.extrabold,
    color: colors.textDark,
  },
  incomingCountdown: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.primaryDark,
  },
  incomingTimerTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryLight,
    overflow: 'hidden',
  },
  incomingTimerFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  incomingInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  acceptButton: {
    minHeight: 68,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16a34a',
  },
  incomingLaterLink: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingLaterText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.semibold,
    textDecorationLine: 'underline',
  },
  checklistStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checklistBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLighter,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  checklistBadgeDone: {
    backgroundColor: '#16a34a',
    borderColor: '#16a34a',
  },
  checklistBadgeText: {
    fontFamily: fonts.bold,
    fontSize: 14,
    color: colors.primaryDark,
  },
  checklistTitleDone: {
    color: colors.textSecondary,
    textDecorationLine: 'line-through',
  },
  connectionBlocked: {
    opacity: 0.45,
  },
  selectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  searchingCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  mechanicBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 18,
    backgroundColor: colors.textDark,
  },
  mechanicBannerTitle: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  mechanicBannerText: {
    color: colors.white,
    opacity: 0.85,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  subtitle: {
    color: colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
    fontSize: 15,
    fontFamily: fonts.regular,
  },
  heroSubtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    textAlign: 'center',
    fontSize: 16,
    fontFamily: fonts.medium,
    paddingHorizontal: 12,
  },
  heroButton: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 28,
    alignSelf: 'center',
    marginTop: 14,
  },
  heroButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  onboardingDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  onboardingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryLight,
  },
  onboardingDotActive: {
    backgroundColor: colors.primary,
    width: 22,
  },
  locationPill: {
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationPin: {
    fontSize: 18,
  },
  locationText: {
    color: colors.textDark,
    fontSize: 15,
    fontFamily: fonts.medium,
    flexShrink: 1,
  },
  profileCard: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    shadowColor: colors.textDark,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarIcon: {
    fontSize: 28,
  },
  profileBody: {
    flex: 1,
    gap: 2,
  },
  profileName: {
    fontSize: 20,
    fontFamily: fonts.bold,
    color: colors.textDark,
  },
  profileMeta: {
    color: colors.textDark,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  expandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  expandLabel: {
    color: colors.primary,
    fontSize: 12,
    fontFamily: fonts.semibold,
  },
  connectionButton: {
    borderRadius: 18,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectionOn: {
    backgroundColor: '#16a34a',
  },
  connectionOff: {
    backgroundColor: '#ef4444',
  },
  emergencyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#ef4444',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  emergencyButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  connectionButtonText: {
    color: colors.white,
    fontSize: 20,
    fontFamily: fonts.extrabold,
    letterSpacing: 0.6,
  },
  sessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  notificationSummary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  notificationBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.warningBg,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  sessionText: {
    flex: 1,
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  card: {
    borderRadius: 20,
    padding: 14,
    gap: 8,
    backgroundColor: colors.white,
    shadowColor: colors.textDark,
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  cardTitle: {
    fontSize: 19,
    fontFamily: fonts.extrabold,
    color: colors.textDark,
  },
  cardSubtitle: {
    color: colors.textDark,
    fontSize: 15,
    fontFamily: fonts.regular,
  },
  identityHint: {
    color: colors.primaryDark,
    fontSize: 14,
    marginBottom: 8,
    fontFamily: fonts.regular,
  },
  stack: {
    gap: 8,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  flex: {
    flex: 1,
  },
  label: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: colors.textDark,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 17,
    fontFamily: fonts.regular,
    color: colors.textDark,
    backgroundColor: colors.primaryLighter,
    minHeight: 52,
  },
  segmented: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  segment: {
    flexGrow: 1,
    flexBasis: '30%',
    minHeight: 54,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
  },
  segmentOnBackground: {
    backgroundColor: colors.white,
  },
  segmentActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  segmentText: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontSize: 15,
  },
  segmentTextActive: {
    color: colors.primaryDark,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.2,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  primaryButtonBusy: {
    opacity: 0.7,
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryLighter,
  },
  menuRowLabel: {
    flex: 1,
    fontSize: 16,
    fontFamily: fonts.medium,
    color: colors.textDark,
  },
  menuRowBadge: {
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  menuRowBadgeText: {
    color: colors.primaryDark,
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  primaryButtonText: {
    color: colors.white,
    fontFamily: fonts.extrabold,
    fontSize: 17,
  },
  secondaryButton: {
    backgroundColor: colors.primaryLighter,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  secondaryButtonCompact: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 120,
    minHeight: 44,
  },
  secondaryButtonTextCompact: {
    fontSize: 15,
  },
  list: {
    gap: 12,
  },
  item: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 8,
  },
  chatBubble: {
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
  },
  chatBubbleCustomer: {
    backgroundColor: colors.primaryLighter,
    borderColor: colors.primaryLighter,
  },
  chatBubbleMechanic: {
    backgroundColor: '#d9f3e4',
    borderColor: '#92d6ad',
  },
  chatBubbleAdmin: {
    backgroundColor: colors.warningBg,
    borderColor: colors.accent,
  },
  chatSender: {
    color: colors.textDark,
    fontSize: 12,
    fontFamily: fonts.extrabold,
  },
  notificationItem: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 6,
  },
  notificationItemRead: {
    opacity: 0.72,
  },
  itemTitle: {
    fontFamily: fonts.extrabold,
    fontSize: 17,
    color: colors.textDark,
  },
  itemText: {
    color: colors.textDark,
    fontSize: 16,
    fontFamily: fonts.regular,
  },
  smallText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  publicProfileBox: {
    gap: 8,
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  publicProfileTitle: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  coverPhoto: {
    width: '100%',
    height: 150,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: colors.primaryLighter,
  },
  galleryRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  galleryPhoto: {
    width: 92,
    height: 92,
    borderRadius: 12,
    backgroundColor: colors.primaryLighter,
  },
  reviewCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 4,
  },
  reviewTitle: {
    color: colors.textDark,
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  calendarStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  calendarChip: {
    minWidth: 70,
    minHeight: 62,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarChipActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  calendarChipText: {
    color: colors.textDark,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  calendarChipTextActive: {
    color: colors.primaryDark,
  },
  slotRow: {
    gap: 6,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: colors.primaryLight,
  },
  slotCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 4,
  },
  slotCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusPillText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  toastWrap: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 24,
    left: 16,
    right: 16,
    zIndex: 50,
    alignItems: 'center',
  },
  toastCard: {
    maxWidth: 480,
    width: '100%',
    backgroundColor: colors.textDark,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  toastText: {
    color: colors.white,
    fontSize: 15,
    fontFamily: fonts.semibold,
    textAlign: 'center',
  },
  badge: {
    color: colors.textDark,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  bottomNavDock: {
    backgroundColor: 'transparent',
  },
  bottomNav: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.primaryLighter,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'android' ? 10 : 4,
    paddingHorizontal: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottomNavItem: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: fonts.semibold,
    letterSpacing: 0.1,
    marginTop: 3,
  },
  bottomNavItemActive: {
    color: colors.primary,
  },
  bottomNavButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
});
