import { Platform, StyleSheet } from 'react-native';
import { colors } from './colors';
import { fonts } from './fonts';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.bgApp,
  },
  safeAreaInner: {
    flex: 1,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 10,
    gap: 14,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 8,
  },
  appShell: {
    gap: 14,
    width: '100%',
  },
  kicker: {
    color: colors.primary,
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontSize: 28,
  },
  serverWakingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.white,
  },
  serverWakingText: {
    flex: 1,
    color: colors.textDark,
    fontSize: 14,
    fontFamily: fonts.semibold,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  topBarGreeting: {
    flexShrink: 1,
    textAlign: 'right',
    fontSize: 15,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  topBarRight: {
    flexShrink: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bellButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  bellButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLighter,
  },
  bellBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.bgApp,
  },
  bellBadgeText: {
    fontFamily: fonts.bold,
    fontSize: 10,
    color: colors.white,
  },
  topBarGreetingName: {
    fontFamily: fonts.bold,
    color: colors.textDark,
  },
  logoWordmark: {
    alignSelf: 'flex-start',
    width: 130,
    height: 25,
  },
  // En la barra de arriba: centrado con el saludo y la campana.
  updateBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 8,
  },
  updateBannerText: {
    flex: 1,
    color: colors.white,
    fontFamily: fonts.semibold,
    fontSize: 14,
  },
  consentText: {
    textAlign: 'left',
  },
  consentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  forgotPasswordLink: {
    alignSelf: 'center',
    paddingVertical: 6,
  },
  topBarLogo: {
    alignSelf: 'center',
  },
  title: {
    fontSize: 24,
    fontFamily: fonts.extrabold,
    color: colors.textDark,
    textAlign: 'center',
  },
  onboardingIconWrap: {
    alignSelf: 'center',
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeHeroImage: {
    alignSelf: 'center',
    width: '100%',
    height: 200,
    marginVertical: 12,
    borderRadius: 20,
    overflow: 'hidden',
  },
  heroPlaceholder: {
    width: '100%',
    height: 160,
    borderRadius: 20,
    marginVertical: 12,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoAddTile: {
    height: 150,
    marginVertical: 0,
    gap: 8,
  },
  photoAddText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  galleryAddTile: {
    width: 92,
    height: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    backgroundColor: colors.primaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryAddText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 12,
  },
  photoRemoveButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(11,15,34,0.7)',
  },
  placeholderCompact: {
    height: 110,
    marginVertical: 4,
  },
  illustration: {
    width: '100%',
    height: 180,
    borderRadius: 20,
    marginVertical: 12,
  },
  illustrationCompact: {
    height: 160,
    marginVertical: 4,
  },
  // Color del "papel" de las ilustraciones (su fondo), para enmarcar las que
  // se muestran enteras.
  illustrationFrame: {
    backgroundColor: '#FCFDFC',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  illustrationFill: {
    width: '100%',
    height: '100%',
  },
  screenStack: {
    gap: 14,
  },
  emptyState: {
    alignItems: 'center',
    gap: 6,
  },
  emptyStateTitle: {
    fontFamily: fonts.extrabold,
    fontSize: 17,
    color: colors.textDark,
    textAlign: 'center',
  },
  emptyStateText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontFamily: fonts.regular,
    textAlign: 'center',
    marginBottom: 4,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  infoRowText: {
    flex: 1,
    color: colors.textDark,
    fontSize: 15,
    fontFamily: fonts.regular,
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  itemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  itemActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  statusPillDone: {
    backgroundColor: '#d9f3e4',
    borderColor: '#d9f3e4',
  },
  statusPillTextDone: {
    color: '#15803d',
  },
  statusPillMuted: {
    backgroundColor: colors.primaryLighter,
    borderColor: colors.primaryLight,
  },
  statusPillTextMuted: {
    color: colors.textSecondary,
  },
  trustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  trustBadge: {
    flexGrow: 1,
    flexBasis: '46%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  trustBadgeText: {
    flex: 1,
    fontSize: 12,
    fontFamily: fonts.semibold,
    color: colors.textDark,
  },
  whenOption: {
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
    gap: 4,
  },
  choiceHalf: {
    flexGrow: 1,
    flexBasis: '46%',
  },
  whenOptionActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  whenOptionTitle: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: colors.textDark,
  },
  whenOptionTitleActive: {
    color: colors.primaryDark,
  },
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  backButtonSpacer: {
    width: 44,
    height: 44,
  },
  progressList: {
    gap: 10,
    paddingVertical: 4,
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.primaryLight,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDotDone: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  progressDotActive: {
    backgroundColor: colors.white,
    borderWidth: 5,
  },
  progressLabel: {
    fontSize: 15,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  progressLabelDone: {
    color: colors.textDark,
  },
  progressLabelActive: {
    fontFamily: fonts.bold,
    color: colors.primaryDark,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  callButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#16a34a',
  },
  callButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  nextStepButton: {
    minHeight: 64,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
  },
  nextStepButtonText: {
    color: colors.white,
    fontFamily: fonts.extrabold,
    fontSize: 19,
    letterSpacing: 0.3,
  },
  incomingScreen: {
    flex: 1,
    backgroundColor: colors.bgApp,
    paddingHorizontal: 16,
    paddingVertical: 20,
    justifyContent: 'space-between',
    gap: 16,
  },
  incomingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  incomingTitle: {
    fontSize: 28,
    fontFamily: fonts.extrabold,
    color: colors.textDark,
  },
  incomingCountdown: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.primaryDark,
  },
  incomingTimerTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryLight,
    overflow: 'hidden',
  },
  incomingTimerFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  incomingInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  acceptButton: {
    minHeight: 68,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16a34a',
  },
  incomingLaterLink: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingLaterText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.semibold,
    textDecorationLine: 'underline',
  },
  checklistStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checklistBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLighter,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  checklistBadgeDone: {
    backgroundColor: '#16a34a',
    borderColor: '#16a34a',
  },
  checklistBadgeText: {
    fontFamily: fonts.bold,
    fontSize: 14,
    color: colors.primaryDark,
  },
  checklistTitleDone: {
    color: colors.textSecondary,
    textDecorationLine: 'line-through',
  },
  selectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  searchingCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  // "¿Qué sigue?" (components/ServiceGuide.tsx): lo que le toca a cada quien.
  guideCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  guideCardWarning: {
    backgroundColor: colors.warningBg,
    borderColor: colors.accent,
  },
  guideIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  guideIconWarning: {
    backgroundColor: colors.accent,
  },
  guideLabel: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  // Tickets de refacciones (components/PartsReceipts.tsx).
  receiptRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  receiptThumb: {
    width: 64,
    height: 84,
    borderRadius: 10,
    backgroundColor: colors.primaryLight,
  },
  receiptPendingText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
  },
  photoViewer: {
    flex: 1,
    backgroundColor: 'rgba(11, 15, 34, 0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  photoViewerImage: {
    width: '100%',
    height: '85%',
  },
  photoViewerClose: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
  },
  photoViewerCloseText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  // Cobro al terminar: el monto grande y su desglose.
  amountValue: {
    color: colors.textDark,
    fontFamily: fonts.extrabold,
    fontSize: 34,
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  breakdownTotal: {
    borderTopWidth: 1,
    borderTopColor: colors.primaryLight,
    paddingTop: 8,
  },
  mechanicBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 18,
    backgroundColor: colors.textDark,
  },
  mechanicBannerTitle: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  mechanicBannerText: {
    color: colors.white,
    opacity: 0.85,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  subtitle: {
    color: colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
    fontSize: 15,
    fontFamily: fonts.regular,
  },
  heroSubtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    textAlign: 'center',
    fontSize: 16,
    fontFamily: fonts.medium,
    paddingHorizontal: 12,
  },
  heroButton: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 28,
    alignSelf: 'center',
    marginTop: 14,
  },
  heroButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  onboardingDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  onboardingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryLight,
  },
  onboardingDotActive: {
    backgroundColor: colors.primary,
    width: 22,
  },
  locationPill: {
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  locationPin: {
    fontSize: 18,
  },
  locationText: {
    color: colors.textDark,
    fontSize: 15,
    fontFamily: fonts.medium,
    flexShrink: 1,
  },
  profileCard: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    borderRadius: 18,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    shadowColor: colors.textDark,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarIcon: {
    fontSize: 28,
  },
  avatarImage: {
    backgroundColor: colors.primaryLight,
  },
  // Tendencias de solicitudes (components/MarketInsights.tsx).
  trendTiles: {
    flexDirection: 'row',
    gap: 10,
  },
  trendTile: {
    flex: 1,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    gap: 2,
  },
  trendValue: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 26,
    fontVariant: ['tabular-nums'],
  },
  trendLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: 13,
  },
  trendChart: {
    height: 120,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryLight,
  },
  trendBarSlot: {
    flex: 1,
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  trendBar: {
    width: '100%',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    backgroundColor: colors.primary,
  },
  trendBarNow: {
    backgroundColor: colors.accent,
  },
  trendBarSelected: {
    backgroundColor: colors.primaryDark,
  },
  trendNowLabel: {
    position: 'absolute',
    top: 0,
    width: 44,
    textAlign: 'center',
    color: colors.textDark,
    fontFamily: fonts.semibold,
    fontSize: 10,
  },
  trendAxis: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  trendAxisLabel: {
    width: '25%',
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: 11,
  },
  trendZoneRow: {
    gap: 4,
  },
  trendZoneHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trendZoneTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primaryLighter,
    overflow: 'hidden',
  },
  trendZoneFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  // "Completa tu perfil" (components/ProfileChecklist.tsx).
  checklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 6,
  },
  checklistDone: {
    color: colors.textSecondary,
    textDecorationLine: 'line-through',
  },
  // Recorrido de la app (components/AppTour.tsx).
  tourLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 50,
    elevation: 50,
  },
  tourOverlay: {
    flex: 1,
  },
  tourDim: {
    position: 'absolute',
    backgroundColor: 'rgba(11,31,51,0.74)',
  },
  tourRing: {
    position: 'absolute',
    borderRadius: 16,
    borderWidth: 3,
    borderColor: colors.accent,
  },
  tourCard: {
    position: 'absolute',
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 18,
    gap: 8,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  tourIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.primaryLighter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tourCounter: {
    color: colors.primaryDark,
    fontFamily: fonts.semibold,
    fontSize: 12,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  tourTitle: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 20,
  },
  tourText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 22,
  },
  tourActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  tourButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  tourNext: {
    minWidth: 140,
  },
  tourSkip: {
    color: colors.textSecondary,
    fontFamily: fonts.semibold,
    fontSize: 15,
  },
  tourBack: {
    color: colors.primaryDark,
    fontFamily: fonts.semibold,
    fontSize: 15,
  },
  avatarInitials: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
  },
  profilePhotoPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  profileBody: {
    flex: 1,
    gap: 2,
  },
  profileName: {
    fontSize: 20,
    fontFamily: fonts.bold,
    color: colors.textDark,
  },
  profileMeta: {
    color: colors.textDark,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  expandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  expandLabel: {
    color: colors.primary,
    fontSize: 12,
    fontFamily: fonts.semibold,
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  connectionDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.textSecondary,
  },
  connectionDotOn: {
    backgroundColor: '#16a34a',
  },
  pulseDotWrap: {
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pulseRing: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#16a34a',
  },
  connectionStatusText: {
    fontFamily: fonts.bold,
    fontSize: 17,
    color: colors.textDark,
  },
  emergencyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#ef4444',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  emergencyButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  sessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  notificationSummary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sessionText: {
    flex: 1,
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  card: {
    borderRadius: 20,
    padding: 14,
    gap: 8,
    backgroundColor: colors.white,
    shadowColor: colors.textDark,
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  cardTitle: {
    fontSize: 19,
    fontFamily: fonts.extrabold,
    color: colors.textDark,
  },
  cardSubtitle: {
    color: colors.textDark,
    fontSize: 15,
    fontFamily: fonts.regular,
  },
  identityHint: {
    color: colors.primaryDark,
    fontSize: 14,
    marginBottom: 8,
    fontFamily: fonts.regular,
  },
  stack: {
    gap: 8,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  flex: {
    flex: 1,
  },
  label: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: colors.textDark,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.primaryLight,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 17,
    fontFamily: fonts.regular,
    color: colors.textDark,
    backgroundColor: colors.primaryLighter,
    minHeight: 52,
  },
  segmented: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  segment: {
    flexGrow: 1,
    flexBasis: '30%',
    minHeight: 54,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
  },
  segmentOnBackground: {
    backgroundColor: colors.white,
  },
  segmentActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  segmentText: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontSize: 15,
  },
  segmentTextActive: {
    color: colors.primaryDark,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: colors.primaryDark,
    shadowOpacity: 0.2,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  primaryButtonBusy: {
    opacity: 0.7,
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryLighter,
  },
  chipRow: {
    gap: 8,
    paddingVertical: 2,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
  },
  categoryChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  categoryChipText: {
    color: colors.textDark,
    fontFamily: fonts.semibold,
    fontSize: 14,
  },
  categoryChipTextActive: {
    color: colors.primaryDark,
  },
  reactionButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.white,
  },
  reactionButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  reactionText: {
    color: colors.primaryDark,
    fontFamily: fonts.semibold,
    fontSize: 14,
  },
  dangerBox: {
    gap: 8,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#f5c2c2',
    backgroundColor: colors.white,
  },
  dangerButton: {
    minHeight: 52,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ef4444',
  },
  dangerButtonText: {
    color: colors.white,
    fontFamily: fonts.extrabold,
    fontSize: 16,
  },
  favoriteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    backgroundColor: colors.primaryLighter,
  },
  favoriteButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  favoriteButtonText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  consentNote: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.regular,
    textAlign: 'center',
  },
  textLink: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    textDecorationLine: 'underline',
  },
  authDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.primaryLight,
  },
  socialButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuPanel: {
    marginTop: 4,
    marginBottom: 8,
  },
  menuRowLabel: {
    flex: 1,
    fontSize: 16,
    fontFamily: fonts.medium,
    color: colors.textDark,
  },
  menuRowBadge: {
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  menuRowBadgeText: {
    color: colors.primaryDark,
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  primaryButtonText: {
    color: colors.white,
    fontFamily: fonts.extrabold,
    fontSize: 17,
  },
  secondaryButton: {
    backgroundColor: colors.primaryLighter,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    minHeight: 52,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  secondaryButtonCompact: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 120,
    minHeight: 44,
  },
  secondaryButtonTextCompact: {
    fontSize: 15,
  },
  list: {
    gap: 12,
  },
  item: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 8,
  },
  chatBubble: {
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
  },
  chatBubbleCustomer: {
    backgroundColor: colors.primaryLighter,
    borderColor: colors.primaryLighter,
  },
  chatBubbleMechanic: {
    backgroundColor: '#d9f3e4',
    borderColor: '#92d6ad',
  },
  chatBubbleAdmin: {
    backgroundColor: colors.warningBg,
    borderColor: colors.accent,
  },
  chatSender: {
    color: colors.textDark,
    fontSize: 12,
    fontFamily: fonts.extrabold,
  },
  notificationItem: {
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 6,
  },
  notificationItemRead: {
    opacity: 0.72,
  },
  // Aviso plegado: una línea (título y fecha); al tocarlo se despliega.
  notificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 36,
  },
  notificationTitle: {
    flex: 1,
    color: colors.textDark,
    fontFamily: fonts.semibold,
    fontSize: 15,
  },
  notificationTitleUnread: {
    fontFamily: fonts.extrabold,
  },
  notificationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  itemTitle: {
    fontFamily: fonts.extrabold,
    fontSize: 17,
    color: colors.textDark,
  },
  itemText: {
    color: colors.textDark,
    fontSize: 16,
    fontFamily: fonts.regular,
  },
  smallText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  publicProfileBox: {
    gap: 8,
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
  },
  publicProfileTitle: {
    color: colors.textDark,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  coverPhoto: {
    width: '100%',
    height: 150,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: colors.primaryLighter,
  },
  galleryRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  galleryPhoto: {
    width: 92,
    height: 92,
    borderRadius: 12,
    backgroundColor: colors.primaryLighter,
  },
  reviewCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 4,
  },
  reviewTitle: {
    color: colors.textDark,
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  reviewStars: {
    color: colors.accent,
  },
  starRating: {
    alignItems: 'center',
    gap: 6,
  },
  starRow: {
    flexDirection: 'row',
    gap: 6,
  },
  starButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Halo y resplandor con el dorado de la paleta (colors.accent, #F2B84B).
  starHalo: {
    position: 'absolute',
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(242, 184, 75, 0.45)',
  },
  starGlow: {
    textShadowColor: 'rgba(242, 184, 75, 0.9)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  starRatingLabel: {
    fontFamily: fonts.semibold,
    fontSize: 14,
    color: colors.textSecondary,
  },
  calendarStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  calendarChip: {
    minWidth: 70,
    minHeight: 62,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.primaryLighter,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarChipActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  calendarChipText: {
    color: colors.textDark,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  calendarChipTextActive: {
    color: colors.primaryDark,
  },
  slotRow: {
    gap: 6,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: colors.primaryLight,
  },
  slotCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    gap: 4,
  },
  slotCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primaryLight,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusPillText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  toastWrap: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 24,
    left: 16,
    right: 16,
    zIndex: 50,
    alignItems: 'center',
  },
  toastCard: {
    maxWidth: 480,
    width: '100%',
    backgroundColor: colors.textDark,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  toastText: {
    color: colors.white,
    fontSize: 15,
    fontFamily: fonts.semibold,
    textAlign: 'center',
  },
  badge: {
    color: colors.textDark,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  bottomNavDock: {
    backgroundColor: 'transparent',
  },
  bottomNav: {
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.primaryLighter,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'android' ? 10 : 4,
    paddingHorizontal: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottomNavItem: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: fonts.semibold,
    letterSpacing: 0.1,
    marginTop: 3,
  },
  bottomNavItemActive: {
    color: colors.primary,
  },
  // Contenedor de un botón de la barra que el recorrido señala (TourTarget).
  bottomNavSlot: {
    flex: 1,
  },
  bottomNavButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
});
