-- Supabase Postgres schema for Mecanifique core entities
-- Run this in the project SQL editor or via the CLI against the target database.

create extension if not exists pgcrypto;

create table if not exists public.mechanics (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  city text not null,
  zone text not null,
  years_experience integer not null default 0,
  specialties text not null default '',
  status text not null default 'pending_verification' check (status in ('pending_verification', 'active', 'suspended')),
  is_available boolean not null default false,
  is_online boolean not null default false,
  latitude double precision,
  longitude double precision,
  rating double precision not null default 5.0,
  jobs_completed integer not null default 0,
  bio text,
  cover_photo_url text,
  gallery_json jsonb not null default '[]'::jsonb,
  review_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('customer', 'mechanic', 'admin')),
  login text not null unique,
  supabase_user_id text unique,
  full_name text not null,
  password_salt text,
  password_hash text,
  customer_id bigint references public.customers(id) on delete cascade,
  mechanic_id bigint references public.mechanics(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.vehicle_profiles (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  nickname text,
  make text not null,
  model text not null,
  year integer not null check (year between 1886 and 2100),
  license_plate text,
  color text,
  mileage integer,
  photo_urls_json jsonb not null default '[]'::jsonb,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id),
  vehicle_make text not null,
  vehicle_model text not null,
  vehicle_year integer not null,
  issue_description text not null,
  preferred_time text not null,
  city text not null,
  zone text not null,
  service_address text,
  latitude double precision,
  longitude double precision,
  status text not null default 'pending' check (status in ('pending', 'assigned', 'in_progress', 'en_route', 'on_site', 'diagnosing', 'repairing', 'awaiting_parts', 'completed', 'cancelled')),
  mechanic_id bigint references public.mechanics(id),
  diagnosis_notes text,
  repair_notes text,
  estimated_price numeric(10,2),
  final_price numeric(10,2),
  hold_expires_at timestamptz,
  schedule_slot_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_request_updates (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests(id) on delete cascade,
  source text not null check (source in ('mechanic', 'system')),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.service_request_messages (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests(id) on delete cascade,
  sender_user_id bigint not null references public.users(id),
  sender_role text not null check (sender_role in ('customer', 'mechanic', 'admin')),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mechanic_schedule_slots (
  id bigint generated by default as identity primary key,
  mechanic_id bigint not null references public.mechanics(id) on delete cascade,
  slot_date date not null,
  start_time text not null,
  end_time text not null,
  status text not null default 'available' check (status in ('available', 'reserved', 'blocked')),
  service_request_id bigint references public.service_requests(id),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.mechanic_reviews (
  id bigint generated by default as identity primary key,
  mechanic_id bigint not null references public.mechanics(id) on delete cascade,
  service_request_id bigint not null unique references public.service_requests(id) on delete cascade,
  customer_user_id bigint not null references public.users(id),
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  body text not null,
  data_json jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  push_token text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists idx_mechanics_city_zone on public.mechanics(city, zone);
create index if not exists idx_service_requests_customer on public.service_requests(customer_id);
create index if not exists idx_service_requests_mechanic on public.service_requests(mechanic_id);
create index if not exists idx_service_requests_status on public.service_requests(status);
create index if not exists idx_notifications_user on public.notifications(user_id, created_at desc);
