-- Verification records contain only object-storage keys. Never store document
-- binaries or public document URLs in the database.
create table if not exists public.identity_verifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  role text not null check (role in ('customer', 'mechanic')),
  status text not null default 'draft'
    check (status in ('draft', 'submitted', 'under_review', 'approved', 'rejected')),
  consent_at timestamptz not null,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by_user_id bigint references public.users(id),
  reviewer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.identity_verification_documents (
  id bigint generated by default as identity primary key,
  verification_id bigint not null references public.identity_verifications(id) on delete cascade,
  document_type text not null check (document_type in (
    'ine_front', 'ine_back', 'selfie', 'proof_of_address', 'criminal_record'
  )),
  storage_key text not null,
  created_at timestamptz not null default now(),
  unique(verification_id, document_type)
);

create index if not exists idx_identity_verifications_status
  on public.identity_verifications(status, updated_at);
