-- Modelo de pagos: apartado + ajuste (ver README.md, sección "Modelo de
-- pagos y apartado"). Añade la tarifa/apartado del mecánico, los campos de
-- seguimiento del apartado/extra/reembolso en cada solicitud, y la tabla de
-- historial de movimientos de dinero reales.

alter table public.mechanics
  add column if not exists labor_rate numeric(10,2);
-- Tarifa fija de mano de obra en MXN, definida por el propio mecánico.
-- También funciona como su apartado mínimo por defecto.

alter table public.service_requests
  add column if not exists deposit_amount numeric(10,2),
  add column if not exists extra_amount numeric(10,2),
  add column if not exists extra_status text
    check (extra_status in ('pending', 'accepted', 'rejected')),
  add column if not exists refund_amount numeric(10,2);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests(id),
  kind text not null check (kind in ('deposit_authorization', 'deposit_capture', 'extra_charge', 'refund')),
  amount numeric(10,2) not null,
  status text not null default 'pending' check (status in ('pending', 'succeeded', 'failed', 'cancelled')),
  provider text,
  provider_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_payments_service_request on public.payments(service_request_id);