-- Disputas: el cliente reporta un problema con un servicio ya realizado.
-- Un admin revisa manualmente y decide la resolución — sin reglas
-- automáticas por ahora (ver README.md). Espejo de la tabla `disputes` de
-- SQLite (ver src/db.ts) que faltaba en el esquema de Supabase.

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  service_request_id bigint not null references public.service_requests(id),
  customer_id bigint not null references public.customers(id),
  category text not null check (category in ('incomplete_work', 'incorrect_charge', 'vehicle_damage', 'other')),
  description text not null,
  status text not null default 'reported' check (status in ('reported', 'under_review', 'resolved')),
  resolution_note text,
  refund_payment_id bigint references public.payments(id),
  resolved_by_user_id bigint references public.users(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_disputes_service_request on public.disputes(service_request_id);
create index if not exists idx_disputes_status on public.disputes(status, created_at);
