-- Registro de auditoría del botón de pánico/911: la llamada real al 911
-- siempre la hace el sistema operativo directo (tel:911), sin pasar por
-- este backend ni depender de él — esto solo deja constancia de quién
-- presionó el botón, desde qué solicitud y con qué ubicación, para que un
-- admin pueda dar seguimiento después. Espejo de `panic_alerts` en SQLite
-- (ver src/db.ts).

create table if not exists public.panic_alerts (
  id bigint generated by default as identity primary key,
  service_request_id bigint references public.service_requests(id),
  reporter_user_id bigint not null references public.users(id),
  reporter_role text not null check (reporter_role in ('customer', 'mechanic', 'admin')),
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create index if not exists idx_panic_alerts_created_at on public.panic_alerts(created_at desc);
